### ISSUE TITLE
Map Coming soon! - not open. Need fix.

### ISSUE THREAD

**Issue by Creater3d** [Sh1penfire/Endless-Rusting-Demo#15]

**Comment by Sh1penfire** [comment]
The mod is unfinished, there will be updates to the main mod
This is purely a demo.

**Comment by Creater3d** [comment]
When will update?

вс, 13 февр. 2022 г. в 13:34, Sh1penfire ***@***.***>:

**Comment by Creater3d** [comment]
>
> On build 126.2 mod see but on 135 not see. When wait or how fix?Message
>> ID: <Sh1penfire/Endless-Rusting-Demo/issue/15/issue_event/6060840116@
>> github.com>
>>
>

Mindustry has crashed. How unfortunate.
Version: release build 126.2
OS: Windows 7 x64
Java Version: 1.8.0_72
Java Architecture: 64
52 Mods: better-vaults:1, cheat:2.2, endless-rusting:_i_ co__u__s a__ 7.1, green-mod:0.1, schematics-pack:8, betamindy:1.07, esoterum:2.11-119, exogenesis:[blue]1.4, exotic-mod:0.7 Alpha, game-info-imager:1.1, gravillaso:2.1.4, hc:1.1, mindus:0.1.0.3, new-horizon:1.10.9.1, prog-mats:23.4, siriuschem-v7:0.42, test-utils:28, unitinfo:1.5.3, 2xconveyors:0.2, aeromindustry:1, backroom:1, better-menders:1, black-floors:1, braindustry:1.4.2, braindustry-java:2, chaos-arranity:4.7 Beta, collos:null, diamond-ore:[#9cb6f4]2.6.0[], dimension-shard:0.24.1, dscape:1.1, emw:1.8.11, goldmod:2.0 alpha b19, green:1, heavy-armaments:2.6, heavy-arsenal:1.1.2, jac:1, larger-cores:1.0, lead_ind:1.5.1, major:2.2, me:1.05, mineralmod:0.9.6.1, powered-by-nature:2.0, revision:12.4, rpm:0.2, sunmod:1.0, the-recompensator-weapon-mod:4.2.0, time-control:0.2, turretsmod:3, upgraded-factories:1.0, vanilla-enhanced:2, vanilla-upgraded:[white]3.0, xelos-pixel-texturepack:0.4.1

mindustry.io.SaveIO$SaveException: java.io.IOException: Error reading region "meta".
	at mindustry.io.SaveIO.load(SaveIO.java:147)
	at mindustry.maps.generators.FileMapGenerator.generate(FileMapGenerator.java:29)
	at mindustry.core.World.lambda$loadSector$0(World.java:249)
	at mindustry.core.World.loadGenerator(World.java:238)
	at mindustry.core.World.loadSector(World.java:247)
	at mindustry.core.Control.lambda$playSector$29(Control.java:400)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:245)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:150)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: java.io.IOException: Error reading region "meta".
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:73)
	at mindustry.io.SaveVersion.read(SaveVersion.java:54)
	at mindustry.io.SaveIO.load(SaveIO.java:160)
	at mindustry.io.SaveIO.load(SaveIO.java:140)
	... 11 more
Caused by: arc.util.serialization.SerializationException: Serialization trace:
{}.sector
sector (mindustry.game.Rules)
	at arc.util.serialization.Json.readFields(Json.java:908)
	at arc.util.serialization.Json.readValue(Json.java:1083)
	at arc.util.serialization.Json.readValue(Json.java:984)
	at arc.util.serialization.Json.fromJson(Json.java:825)
	at mindustry.io.JsonIO.read(JsonIO.java:57)
	at mindustry.io.SaveVersion.readMeta(SaveVersion.java:109)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:121)
	at mindustry.io.SaveFileReader.readChunk(SaveFileReader.java:114)
	at mindustry.io.SaveFileReader.region(SaveFileReader.java:71)
	... 14 more
Caused by: java.lang.NullPointerException
	at mindustry.io.JsonIO$2.read(JsonIO.java:84)
	at mindustry.io.JsonIO$2.read(JsonIO.java:74)
	at arc.util.serialization.Json.readValue(Json.java:1090)
	at arc.util.serialization.Json.readFields(Json.java:901)
	... 22 more
